apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deploy
spec:
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      name: mon-app-pod
      labels:
        app: monapp
    spec:
      hostNetwork: true
      containers:
        - name: mon-app
          image: ashcripps/final-year-project:monapp
          ports:
            - containerPort: 3000
              hostPort: 3000
